/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JokerManager;

import java.awt.Color;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import listeners.Manager_AddEmployee_BT_Employee_Listener;
import listeners.Manager_AddItem_BT_Item_Listener;
import listeners.Manager_AddQuantity_BT_Item_Listener;
import listeners.Manager_Search_BT_Employee_Listener;
import listeners.Manager_Search_BT_Item_Listener;
import listeners.Manager_ViewSales_BT_Employee_Listener;

/**
 *
 * @author JOHN
 */
public class Manager extends javax.swing.JFrame {


    public Manager() {
        initComponents();
        Container a = this.getContentPane();
        a.setBackground(Color.WHITE);
        
        AddEmployee_BT_Employee.addActionListener(new Manager_AddEmployee_BT_Employee_Listener(this));
        AddItem_BT_Item.addActionListener(new Manager_AddItem_BT_Item_Listener(this));
        AddQuantity_BT_Item.addActionListener(new Manager_AddQuantity_BT_Item_Listener(this));
        Search_BT_Employee.addActionListener(new Manager_Search_BT_Employee_Listener(this));
        Search_BT_Item.addActionListener(new Manager_Search_BT_Item_Listener(this));
        ViewSales_BT_Employee.addActionListener(new Manager_ViewSales_BT_Employee_Listener(this));
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductCategory_BG = new javax.swing.ButtonGroup();
        AccssoresCategory_BG = new javax.swing.ButtonGroup();
        TabbedPane = new javax.swing.JTabbedPane();
        Employee_Panel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Employes_Table_Employee = new javax.swing.JTable();
        Employes_LB_Employee = new javax.swing.JLabel();
        AddEmployee_TF_Employee = new javax.swing.JLabel();
        SearchEmployee_LB_Eemployee = new javax.swing.JLabel();
        SearchEmployee_TF_Employee = new javax.swing.JTextField();
        Search_BT_Employee = new javax.swing.JButton();
        EmployeeID_LB_Employee = new javax.swing.JLabel();
        EmployeId_TF_Employee = new javax.swing.JTextField();
        ViewSales_BT_Employee = new javax.swing.JButton();
        AddEmployee_BT_Employee = new javax.swing.JButton();
        Name_LB_Employee = new javax.swing.JLabel();
        Name_TF_Employee = new javax.swing.JTextField();
        UserName_LB_Employee = new javax.swing.JLabel();
        UserName_TF_Employee = new javax.swing.JTextField();
        Password_LB_Employee = new javax.swing.JLabel();
        Password_TF_Employee = new javax.swing.JPasswordField();
        Item_Panel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Items_Table_Item = new javax.swing.JTable();
        Items_LB_Item = new javax.swing.JLabel();
        AddItem_LB_Item = new javax.swing.JLabel();
        SearchItem_LB_Item = new javax.swing.JLabel();
        SearchItem_TF_Itme = new javax.swing.JTextField();
        Search_BT_Item = new javax.swing.JButton();
        ItemID_LB_Item = new javax.swing.JLabel();
        ItmeID_TF_Item = new javax.swing.JTextField();
        AddQuantity_BT_Item = new javax.swing.JButton();
        AddItem_BT_Item = new javax.swing.JButton();
        Name_LB_Item = new javax.swing.JLabel();
        Name_TF_Item = new javax.swing.JTextField();
        BuyingPrice_LB_Item = new javax.swing.JLabel();
        BuyingPrice_TF_Item = new javax.swing.JTextField();
        Price_LB_Item = new javax.swing.JLabel();
        Price_TF_Item = new javax.swing.JTextField();
        Stock_TF_Item = new javax.swing.JTextField();
        Stock_LB_Item = new javax.swing.JLabel();
        Quantity_LB_Item = new javax.swing.JLabel();
        Quantity_TF_Item = new javax.swing.JTextField();
        ManagerName_LB = new javax.swing.JLabel();
        Manager_LB = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Employee_Panel.setBackground(new java.awt.Color(245, 245, 245));

        Employes_Table_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Employes_Table_Employee);
        if (Employes_Table_Employee.getColumnModel().getColumnCount() > 0) {
            Employes_Table_Employee.getColumnModel().getColumn(0).setResizable(false);
            Employes_Table_Employee.getColumnModel().getColumn(1).setResizable(false);
        }

        Employes_LB_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Employes_LB_Employee.setText("Employes:");

        AddEmployee_TF_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddEmployee_TF_Employee.setText("Add New Employee:");

        SearchEmployee_LB_Eemployee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SearchEmployee_LB_Eemployee.setText("Search Employee");

        SearchEmployee_TF_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Search_BT_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Search_BT_Employee.setForeground(new java.awt.Color(102, 102, 102));
        Search_BT_Employee.setText("Search");
        Search_BT_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BT_EmployeeActionPerformed(evt);
            }
        });

        EmployeeID_LB_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        EmployeeID_LB_Employee.setText("Employee ID");

        EmployeId_TF_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        ViewSales_BT_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ViewSales_BT_Employee.setText("View Sales");
        ViewSales_BT_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSales_BT_EmployeeActionPerformed(evt);
            }
        });

        AddEmployee_BT_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddEmployee_BT_Employee.setText("Add Employee");
        AddEmployee_BT_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployee_BT_EmployeeActionPerformed(evt);
            }
        });

        Name_LB_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Name_LB_Employee.setText("Name");

        Name_TF_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        UserName_LB_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UserName_LB_Employee.setText("User Name");

        UserName_TF_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Password_LB_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Password_LB_Employee.setText("Password");

        Password_TF_Employee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Password_TF_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TF_EmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Employee_PanelLayout = new javax.swing.GroupLayout(Employee_Panel);
        Employee_Panel.setLayout(Employee_PanelLayout);
        Employee_PanelLayout.setHorizontalGroup(
            Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Employes_LB_Employee)
                    .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Employee_PanelLayout.createSequentialGroup()
                            .addComponent(SearchEmployee_LB_Eemployee)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SearchEmployee_TF_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Search_BT_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Employee_PanelLayout.createSequentialGroup()
                                .addComponent(EmployeeID_LB_Employee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeId_TF_Employee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ViewSales_BT_Employee)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Employee_PanelLayout.createSequentialGroup()
                        .addComponent(AddEmployee_TF_Employee)
                        .addGap(224, 224, 224))
                    .addGroup(Employee_PanelLayout.createSequentialGroup()
                        .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Password_LB_Employee)
                            .addComponent(UserName_LB_Employee)
                            .addComponent(Name_LB_Employee))
                        .addGap(18, 18, 18)
                        .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddEmployee_BT_Employee, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(Name_TF_Employee)
                            .addComponent(UserName_TF_Employee)
                            .addComponent(Password_TF_Employee))
                        .addGap(162, 162, 162))))
        );
        Employee_PanelLayout.setVerticalGroup(
            Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchEmployee_LB_Eemployee)
                    .addComponent(SearchEmployee_TF_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_BT_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Employes_LB_Employee)
                    .addComponent(AddEmployee_TF_Employee))
                .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Employee_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Employee_PanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name_LB_Employee)
                            .addComponent(Name_TF_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserName_LB_Employee)
                            .addComponent(UserName_TF_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Password_LB_Employee)
                            .addComponent(Password_TF_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AddEmployee_BT_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeID_LB_Employee)
                    .addComponent(EmployeId_TF_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewSales_BT_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Employee", Employee_Panel);

        Item_Panel.setBackground(new java.awt.Color(245, 245, 245));

        Items_Table_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Buying Price", "Price", "Stock ", "Total Purchased"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Items_Table_Item);
        if (Items_Table_Item.getColumnModel().getColumnCount() > 0) {
            Items_Table_Item.getColumnModel().getColumn(0).setResizable(false);
            Items_Table_Item.getColumnModel().getColumn(1).setResizable(false);
            Items_Table_Item.getColumnModel().getColumn(2).setResizable(false);
            Items_Table_Item.getColumnModel().getColumn(3).setResizable(false);
            Items_Table_Item.getColumnModel().getColumn(4).setResizable(false);
            Items_Table_Item.getColumnModel().getColumn(5).setResizable(false);
        }

        Items_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Items_LB_Item.setText("Items:");

        AddItem_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddItem_LB_Item.setText("Add New Item:");

        SearchItem_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SearchItem_LB_Item.setText("Search Item");

        SearchItem_TF_Itme.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Search_BT_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Search_BT_Item.setForeground(new java.awt.Color(102, 102, 102));
        Search_BT_Item.setText("Search");
        Search_BT_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BT_ItemActionPerformed(evt);
            }
        });

        ItemID_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ItemID_LB_Item.setText("Item ID");

        ItmeID_TF_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        AddQuantity_BT_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddQuantity_BT_Item.setText("Add Quantity");
        AddQuantity_BT_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddQuantity_BT_ItemActionPerformed(evt);
            }
        });

        AddItem_BT_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddItem_BT_Item.setText("Add Item");
        AddItem_BT_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItem_BT_ItemActionPerformed(evt);
            }
        });

        Name_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Name_LB_Item.setText("Name");

        Name_TF_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        BuyingPrice_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BuyingPrice_LB_Item.setText("Buying Price");

        BuyingPrice_TF_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Price_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Price_LB_Item.setText("Price");

        Price_TF_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Stock_TF_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Stock_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Stock_LB_Item.setText("Stock");

        Quantity_LB_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Quantity_LB_Item.setText("Quantity");

        Quantity_TF_Item.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout Item_PanelLayout = new javax.swing.GroupLayout(Item_Panel);
        Item_Panel.setLayout(Item_PanelLayout);
        Item_PanelLayout.setHorizontalGroup(
            Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item_PanelLayout.createSequentialGroup()
                        .addComponent(Items_LB_Item)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Item_PanelLayout.createSequentialGroup()
                                .addComponent(AddItem_LB_Item)
                                .addGap(224, 224, 224))
                            .addGroup(Item_PanelLayout.createSequentialGroup()
                                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuyingPrice_LB_Item, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Name_LB_Item, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Price_LB_Item, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Stock_LB_Item, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Name_TF_Item, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(BuyingPrice_TF_Item)
                                    .addComponent(Price_TF_Item)
                                    .addComponent(Stock_TF_Item)
                                    .addComponent(AddItem_BT_Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(162, 162, 162))))
                    .addGroup(Item_PanelLayout.createSequentialGroup()
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Item_PanelLayout.createSequentialGroup()
                                .addComponent(SearchItem_LB_Item)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchItem_TF_Itme, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search_BT_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Item_PanelLayout.createSequentialGroup()
                                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Quantity_LB_Item)
                                    .addComponent(ItemID_LB_Item))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Quantity_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItmeID_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addComponent(AddQuantity_BT_Item)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Item_PanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(475, Short.MAX_VALUE))))
        );
        Item_PanelLayout.setVerticalGroup(
            Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchItem_LB_Item)
                    .addComponent(SearchItem_TF_Itme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_BT_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Items_LB_Item)
                    .addComponent(AddItem_LB_Item))
                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemID_LB_Item)
                            .addComponent(ItmeID_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity_LB_Item)
                            .addComponent(Quantity_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddQuantity_BT_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Item_PanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name_LB_Item))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuyingPrice_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuyingPrice_LB_Item))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price_LB_Item))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stock_TF_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stock_LB_Item))
                        .addGap(18, 18, 18)
                        .addComponent(AddItem_BT_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Item", Item_Panel);

        ManagerName_LB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ManagerName_LB.setText("Manager Name");

        Manager_LB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Manager_LB.setText("Manager :");

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerManager/JokerLogo1.png"))); // NOI18N

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerManager/JokerLogo3.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Manager View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(Manager_LB)
                        .addGap(18, 18, 18)
                        .addComponent(ManagerName_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ManagerName_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Manager_LB))
                            .addGap(31, 31, 31))
                        .addComponent(Logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22)
                .addComponent(TabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_BT_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BT_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_BT_EmployeeActionPerformed

    private void ViewSales_BT_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSales_BT_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewSales_BT_EmployeeActionPerformed

    private void AddEmployee_BT_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployee_BT_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEmployee_BT_EmployeeActionPerformed

    private void Password_TF_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TF_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TF_EmployeeActionPerformed

    private void Search_BT_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BT_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_BT_ItemActionPerformed

    private void AddQuantity_BT_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddQuantity_BT_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddQuantity_BT_ItemActionPerformed

    private void AddItem_BT_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItem_BT_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddItem_BT_ItemActionPerformed
    public void showMsg(String text) {
        JOptionPane.showMessageDialog(null, text);
    }

    public ButtonGroup getAccssoresCategory_BG() {
        return AccssoresCategory_BG;
    }

    public JButton getAddEmployee_BT_Employee() {
        return AddEmployee_BT_Employee;
    }

    public JLabel getAddEmployee_TF_Employee() {
        return AddEmployee_TF_Employee;
    }

    public JButton getAddItem_BT_Item() {
        return AddItem_BT_Item;
    }

    public JLabel getAddItem_LB_Item() {
        return AddItem_LB_Item;
    }

    public JButton getAddQuantity_BT_Item() {
        return AddQuantity_BT_Item;
    }

    public JLabel getBuyingPrice_LB_Item() {
        return BuyingPrice_LB_Item;
    }

    public JTextField getBuyingPrice_TF_Item() {
        return BuyingPrice_TF_Item;
    }

    public JLabel getEmployeeID_LB_Employee() {
        return EmployeeID_LB_Employee;
    }

    public JPanel getEmployee_Panel() {
        return Employee_Panel;
    }

    public JLabel getEmployes_LB_Employee() {
        return Employes_LB_Employee;
    }

    public JTable getEmployes_Table_Employee() {
        return Employes_Table_Employee;
    }

    public JLabel getItemID_LB_Item() {
        return ItemID_LB_Item;
    }

    public JPanel getItem_Panel() {
        return Item_Panel;
    }

    public JLabel getItems_LB_Item() {
        return Items_LB_Item;
    }

    public JTable getItems_Table_Item() {
        return Items_Table_Item;
    }

    public JTextField getEmployeId_TF_Employee() {
        return EmployeId_TF_Employee;
    }


    public JTextField getItmeID_TF_Item() {
        return ItmeID_TF_Item;
    }

    public JLabel getLogo1() {
        return Logo1;
    }

    public JLabel getLogo2() {
        return Logo2;
    }

    public JLabel getManagerName_LB() {
        return ManagerName_LB;
    }

    public JLabel getManager_LB() {
        return Manager_LB;
    }

    public JLabel getName_LB_Employee() {
        return Name_LB_Employee;
    }

    public JLabel getName_LB_Item() {
        return Name_LB_Item;
    }

    public JTextField getName_TF_Employee() {
        return Name_TF_Employee;
    }

    public JTextField getName_TF_Item() {
        return Name_TF_Item;
    }

    public JLabel getPassword_LB_Employee() {
        return Password_LB_Employee;
    }

    public JPasswordField getPassword_TF_Employee() {
        return Password_TF_Employee;
    }

    public JLabel getPrice_LB_Item() {
        return Price_LB_Item;
    }

    public JTextField getPrice_TF_Item() {
        return Price_TF_Item;
    }

    public ButtonGroup getProductCategory_BG() {
        return ProductCategory_BG;
    }

    public JLabel getQuantity_LB_Item() {
        return Quantity_LB_Item;
    }

    public JTextField getQuantity_TF_Item() {
        return Quantity_TF_Item;
    }

    public JLabel getSearchEmployee_LB_Eemployee() {
        return SearchEmployee_LB_Eemployee;
    }

    public JTextField getSearchEmployee_TF_Employee() {
        return SearchEmployee_TF_Employee;
    }

    public JLabel getSearchItem_LB_Item() {
        return SearchItem_LB_Item;
    }

    public JTextField getSearchItem_TF_Itme() {
        return SearchItem_TF_Itme;
    }

    public JButton getSearch_BT_Employee() {
        return Search_BT_Employee;
    }

    public JButton getSearch_BT_Item() {
        return Search_BT_Item;
    }

    public JLabel getStock_LB_Item() {
        return Stock_LB_Item;
    }

    public JTextField getStock_TF_Item() {
        return Stock_TF_Item;
    }

    public JTabbedPane getTabbedPane() {
        return TabbedPane;
    }

    public JLabel getUserName_LB_Employee() {
        return UserName_LB_Employee;
    }

    public JTextField getUserName_TF_Employee() {
        return UserName_TF_Employee;
    }

    public JButton getViewSales_BT_Employee() {
        return ViewSales_BT_Employee;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public JScrollPane getjScrollPane6() {
        return jScrollPane6;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AccssoresCategory_BG;
    private javax.swing.JButton AddEmployee_BT_Employee;
    private javax.swing.JLabel AddEmployee_TF_Employee;
    private javax.swing.JButton AddItem_BT_Item;
    private javax.swing.JLabel AddItem_LB_Item;
    private javax.swing.JButton AddQuantity_BT_Item;
    private javax.swing.JLabel BuyingPrice_LB_Item;
    private javax.swing.JTextField BuyingPrice_TF_Item;
    private javax.swing.JTextField EmployeId_TF_Employee;
    private javax.swing.JLabel EmployeeID_LB_Employee;
    private javax.swing.JPanel Employee_Panel;
    private javax.swing.JLabel Employes_LB_Employee;
    private javax.swing.JTable Employes_Table_Employee;
    private javax.swing.JLabel ItemID_LB_Item;
    private javax.swing.JPanel Item_Panel;
    private javax.swing.JLabel Items_LB_Item;
    private javax.swing.JTable Items_Table_Item;
    private javax.swing.JTextField ItmeID_TF_Item;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel ManagerName_LB;
    private javax.swing.JLabel Manager_LB;
    private javax.swing.JLabel Name_LB_Employee;
    private javax.swing.JLabel Name_LB_Item;
    private javax.swing.JTextField Name_TF_Employee;
    private javax.swing.JTextField Name_TF_Item;
    private javax.swing.JLabel Password_LB_Employee;
    private javax.swing.JPasswordField Password_TF_Employee;
    private javax.swing.JLabel Price_LB_Item;
    private javax.swing.JTextField Price_TF_Item;
    private javax.swing.ButtonGroup ProductCategory_BG;
    private javax.swing.JLabel Quantity_LB_Item;
    private javax.swing.JTextField Quantity_TF_Item;
    private javax.swing.JLabel SearchEmployee_LB_Eemployee;
    private javax.swing.JTextField SearchEmployee_TF_Employee;
    private javax.swing.JLabel SearchItem_LB_Item;
    private javax.swing.JTextField SearchItem_TF_Itme;
    private javax.swing.JButton Search_BT_Employee;
    private javax.swing.JButton Search_BT_Item;
    private javax.swing.JLabel Stock_LB_Item;
    private javax.swing.JTextField Stock_TF_Item;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel UserName_LB_Employee;
    private javax.swing.JTextField UserName_TF_Employee;
    private javax.swing.JButton ViewSales_BT_Employee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
